BE: DYNAMICALLY SOLVING THE TSP

Authors: Guillaume Plobner, Raphael Mikati

Q1: Let us use a distance matrix G to define as a relevant data structure to represent a graph. For any (i,j), G(i,j) is the distance between node i and node j.

In [134]:
import numpy as np
from scipy.spatial.distance import euclidean

import sys

with open("tsp5.txt") as data_file:
    nb=0
    print("expected number of vertices : [0]\n".format(int(data_file.readline())))
    coord = []
   
    for line in data_file:
        print("reading point {0}: {1}".format(nb, tuple(float(x) for x in line.split())))
        nb = nb +1
        coord.append(tuple(float(x) for x in line.split()))
       
    print(" \nnumber of vertices: {0}".format(nb))
    
dist5 = np.zeros((len(coord),len(coord)))

for i in range(len(coord)):
    for j in range(len(coord)):
        dist5[i][j] = euclidean(coord[i], coord[j])
        dist5[j][i] = dist5[i][j]
        

expected number of vertices : [0]

reading point 0: (20833.3333, 17100.0)
reading point 1: (20900.0, 17066.6667)
reading point 2: (21300.0, 13016.6667)
reading point 3: (21600.0, 14150.0)
reading point 4: (21600.0, 14966.6667)
 
number of vertices: 5


Q2: Implementation of Held-Karp's algorithm:

We consider a graph as input and we will consider it a distance matrix G: for any (i,j), G(i,j) is the distance between node i and node j

In [139]:
# Let us import the relevant packages
import itertools
import numpy as np

# The below function is used to compute the minimum elements required in the Held-Karp algorithm 
def min_within_subset(subset,j, L, G):
    dist = []
    if j!=0:
        
        inter_subset = set(subset)
        inter_subset.remove(j)
        new_subset = tuple(inter_subset)
    else:
        new_subset = subset
    
    for k in subset:
         
        if k != j :
            dist.append(L[(new_subset, k)]+G[j,k])
           
    return(min(dist))    

# Below, the Held-Karp algorithm aimed at calculating the shortest tour for a given graph G
def held_karp(G):
    n = len(G)
    L = {}
    
    for i in range(1,n):
        L[((i,), i)] = G[0,i]
        
    for subset_size in range(2,n):
        for subset in itertools.combinations(range(1,n), subset_size):
            for j in subset :
                L[(subset,j)] = min_within_subset(subset,j, L, G)
                
    length_shortest_path = min_within_subset(tuple(range(1,n)),0, L, G)
    
    return("The length of the shortest tour for G is: "+str(length_shortest_path))
        

First, we test our algorithm on the example from the lecture notes.

In [136]:
g = np.zeros((4,4))
g[0][0]=0
g[0][1]=2
g[0][2]=1
g[0][3]=4
g[1][0]=2
g[1][1]=0
g[1][2]=3
g[1][3]=5
g[2][0]=1
g[2][1]=3
g[2][2]=0
g[2][3]=6
g[3][0]=4
g[3][1]=5
g[3][2]=6
g[3][3]=0
print(g)

[[ 0.  2.  1.  4.]
 [ 2.  0.  3.  5.]
 [ 1.  3.  0.  6.]
 [ 4.  5.  6.  0.]]


Our algorithm works on this example!

In [137]:
held_karp(g)

'The length of the shortest tour for G is: 13.0'

Q3: Let us test the algorithm on the provided files

In [138]:
held_karp(dist5)

'The length of the shortest tour for G is: 8387.07713028'